version: "3.8"

networks:
  elastic:
    driver: bridge

volumes:
  output_data:
    name: "output_data"
  tools_conf:
    name: "tools_conf"

services:
  osint-container:
    image: osint-collector
    ports:
      - "8080:8080"
  neo4j:
    image: neo4j:4.1.0
    container_name: "neo4j-test-2"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_use__neo4j__config=true