version: "3.8"

networks:
  elastic:
    driver: bridge

volumes:
  tools_output_data:
    name: "tools_output_data"
  pipeline_output_data:
    name: "pipeline_output_data"

services:

  flask:
    user: root
    image: flask_launcher
    build: ./launcher
    container_name: flask_launcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tools_output_data:/app/output/
    ports:
      - 5000:5000
    networks:
      - elastic

  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:8.12.0
    container_name: filebeat
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./pipeline/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - tools_output_data:/usr/share/filebeat/ingest_data
    networks:
      - elastic

  logstash:
    user: root
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    environment:
      xpack.monitoring.enabled: false
      log.level: debug
    volumes:
      - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - pipeline_output_data:/usr/share/logstash/output_data/
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    networks:
      - elastic
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf