version: '3'

services:

  # Description: Download all the data from the given instagram account; only works with public account.
  instaloader:
    extends: common   
    entrypoint: ./instaloader.py --login --dirname-pattern=/output/${LAUNCHER_INPUT} profile ${LAUNCHER_INPUT}

  # Description: Download all the messages from the given telegram channel.
  snscrape-telegram:
    extends: common
    entrypoint: sh -c "snscrape --jsonl telegram-channel ${LAUNCHER_INPUT} > /output/${LAUNCHER_INPUT}.jsonl"
  
  # Description: Search on DuckDuckGo all the information about the given domain (emails, IPs and Hosts).
  the-harvester:
    extends: common
    entrypoint: ./theHarvester.py -d ${LAUNCHER_INPUT} -b duckduckgo -f /output/${LAUNCHER_INPUT}.json

  # A common service to build and run the tools.
  common:
    build: ./tools/${LAUNCHER_TOOL}
    image: ${LAUNCHER_TOOL}
    container_name: ${LAUNCHER_TOOL}
    volumes:
      - ./output/${LAUNCHER_TOOL}:/output