# Use export INPUT=instagram_profile_name to set the profile name

version: '3'

services:

  instaloader:
    build: ./tools/instaloader
    image: instaloader
    container_name: instaloader
    volumes:
      - ./output/instaloader:/app/${LAUNCHER_INPUT}
    entrypoint: ./instaloader.py
    command: profile ${LAUNCHER_INPUT}
