version: '3'

services:

  instaloader:
    extends: common

  snscrape-telegram:
    extends: common
  
  the-harvester:
    extends: common

  # A common service to build and run the tools.
  common:
    build: 
      context: ./tools/${LAUNCHER_TOOL}
      dockerfile: ${LAUNCHER_TOOL}.Dockerfile
    image: ${LAUNCHER_TOOL}
    container_name: ${LAUNCHER_TOOL}
    entrypoint: ${LAUNCHER_ENTRYPOINT}
    volumes:
      - ./output/${LAUNCHER_TOOL}:/output