version: "3.8"

networks:
  elastic:
    driver: bridge

volumes:
  output_data:
    name: "output_data"
  tools_conf:
    name: "tools_conf"

services:

  launcher:
    user: root
    image: launcher
    build: ./launcher
    container_name: launcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./launcher:/app
      - output_data:/app/output/
      - tools_conf:/tools_conf
    ports:
      - 5000:5000
    networks:
      - elastic
    command: ./main.py