version: '3'

services:

  instaloader:
    build: ./tools/instaloader
    image: instaloader
    container_name: instaloader
    volumes:
      - ./output/instaloader:/app/${LAUNCHER_INPUT}
    entrypoint: ./instaloader.py profile ${LAUNCHER_INPUT}

  snscrape-telegram:
    build: ./tools/snscrape
    image: snscrape
    container_name: snscrape-telegram
    volumes:
      - ./output/snscrape-telegram:/app/${LAUNCHER_INPUT}
    entrypoint: sh -c "snscrape --jsonl telegram-channel ${LAUNCHER_INPUT} > /app/${LAUNCHER_INPUT}/output.jsonl"

    