version: '3'

services:

  # Description: Download all the data from the given instagram account; only works with public account.
  instaloader:
    extends: common

  # Description: Download the last message from the given telegram channel.
  snscrape-telegram:
    extends: common
  
  # Description: Search on DuckDuckGo all the information about the given domain (emails, IPs and Hosts).
  the-harvester:
    extends: common

  # A common service to build and run the tools.
  common:
    build: 
      context: ./tools/${LAUNCHER_TOOL}
      dockerfile: ${LAUNCHER_TOOL}.Dockerfile
    image: ${LAUNCHER_TOOL}
    container_name: ${LAUNCHER_TOOL}
    entrypoint: ${LAUNCHER_ENTRYPOINT}
    volumes:
      - ./output/${LAUNCHER_TOOL}:/output