sudo: required
dist: xenial
language: python
cache: pip3
python:
  - "3.9"
# command to install dependencies
install:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install
  - cd src/modules/tests
script: 
  - pytest
notifications:
    slack: dedsec-inside:24NHg47gypeVR3DWnEncRq7c
