version: '3.7'
services:
  neo4j:
    image: neo4j:4.0.7-enterprise
    container_name: "neo4j"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/password
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
      # - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc", "n10s"]