# Use export INPUT=instagram_profile_name to set the profile name

version: '3'

services:

  instaloader:
    build: .
    image: instaloader
    container_name: instaloader
    volumes:
      - ./output:/app/${LAUNCHER_INPUT}
    command: profile ${LAUNCHER_INPUT}
